Added Next Button Component
UdacityMobileWebScholarship/guess-quote pull request #65
Opened 2018-05-06 16:10 UTC by PN1019

Well, As  discussed on  [issue](https://github.com/UdacityMobileWebScholarship/guess-quote/issues/56), i have created NextButton Component 
![nextbutton](https://user-images.githubusercontent.com/16081831/39675242-2525a6f8-510d-11e8-9791-eb410f23c8de.png)

2018-05-08 12:19 UTC, twishasaraiya requested changes

2018-05-08 12:19 UTC, twishasaraiya commented on client/src/components/NextButton.test.js
> +});
Please remove the test file.

2018-05-08 12:19 UTC, twishasaraiya commented on client/src/containers/SampleContainer/SampleContainer.js
> +        <NextButton disabled />)
Only call `NextButton` here while testing. It will not be called from here in actual code. You can make a separate PR later to call it from `QuoteNOptions`.

2018-05-09 07:43 UTC, skyshader commented
This PR doesn't add anything to the goal of this project. To make it more relevant, please attach some behaviour to it, like actually going to the next screen for certain number of screens and when reached at the end, disable it.

2018-05-13 17:53 UTC, twishasaraiya commented
@PN1019 I think you can work on `nextButton` and `AnswerComponent` since the PR for `QuoteNOptionComponent` is merged.

2020-11-16 13:36 UTC, PN1019 commented
Since the project is no longer active  I am closing this PR.

2020-11-16 13:36 UTC, closed without merging